 # You can use HEX, GRADIENTS and RAINBOW COLORS in all of these messages
 # HEX COLOR: <SOLID:00FFD3>TEXT
 # GRADIENT COLOR: <GRADIENT:2C08BA>TEXT</GRADIENT:028A97>
 # RAINBOW COLOR: <RAINBOW1>TEXT</RAINBOW>

commands:
  free:
    description: "Command for free Items"

    console:
      - "give %player% diamond 1"
      - "give %player% emerald 1"

    use: "&fYou got a &bdiamond &fand &aemerald&f."
    used: "&c&l[!] &fYou reached max uses"

    permission: ""
    join:
      enabled: true
      message:
        - "&e--------------------"
        - "&fYou didn't pick up your free reward"
        - "&fUse &e/free"
        - "&e--------------------"

onlyPlayer: "&c&l[!] &fThis command is only for player."

reloading: "&c&l[!] &fThe &cCMDLimit &fplugin is &creloading&f!"
reloadComplete: "&a&l[!] &fCMDLimit reload is &acomplete&f!"
noPermission: "&c&l[!] &fYou don´t have permission to use &c/%command%&f!"