 # You can use HEX, GRADIENTS and RAINBOW COLORS in all of these messages
 # HEX COLOR: <SOLID:00FFD3>TEXT
 # GRADIENT COLOR: <GRADIENT:2C08BA>TEXT</GRADIENT:028A97>
 # RAINBOW COLOR: <RAINBOW1>TEXT</RAINBOW>
updateChecker: true
dateFormat: "dd.MM.yyyy HH:mm:ss" # required restart

commands:
  free:
    description: "Command for free Items"

    console:
      - "give %player% diamond 1"
      - "give %player% emerald 1"

    maxUse: 3

    minimumRequirements: 3

    requirements:
      commandExpiration:
        condition: "dateExpiration:18.07.2024 16:00:00"
        denyMessage: "&c&l[!] &fThis command is expired!"
      playersOnline:
        condition: "%server_online%>1"
        denyMessage: "&c&l[!] &fThere must be more than 1 player on the server"
      hasFly:
        condition: "%player_allow_flight%==no"
        denyMessage: "&c&l[!] &fYou can't use this command while you are flying"

      commandExpirationCheck:
        type: "<=" # currentDate <= 18.07.2024 16:00:00 -> is Before ?
        input: "currentDate"
        output: "18.07.2024 16:00:00"
        denyMessage: "&c&l[!] &fThis command is expired!"
      permissionCheck:
        type: "!=" # permission != cmdlimiter.free
        input: "permission"
        output: "cmdlimiter.free"
        denyMessage: "&c&l[!] &fThere must be more than 1 player on the server"
      flyCheck:
        type: "=="
        input: "%player_allow_flight%"
        output: "&cNe"
        denyMessage: "&c&l[!] &fYou can't use this command while you are flying"


    use: "&fYou got a &bdiamond &fand &aemerald&f."
    used: "&c&l[!] &fYou reached max uses"

    join:
      enabled: true
      message:
        - "&e--------------------"
        - "&fYou didn't pick up your free reward"
        - "&fUse &e/free"
        - "&e--------------------"

help:
  - "&c&lCMDLimiter HELP"
  - "&f- &c/cmdlimiter reload &fReloads the config.yml and data.yml files."
  - "&f- &c/cmdlimiter set <player> [command] <uses> &fSets the number of uses for a specific player."
commandUsage: "&c&l[!] &fUsage: &c%command%&f!"

reloading: "&c&l[!] &fThe &cCMDLimit &fplugin is &creloading&f!"
reloadComplete: "&a&l[!] &fCMDLimit reload is &acomplete&f!"
dataSaved: "&a&l[!] &fCMDLimit data saved&f!"
setPlayerUses: "&a&l[!] &fPlayer &a%player% &fnow has &a%uses% &fuses."

onlyForPlayer: "&c&l[!] &fThis command is only for player."
playerNotFound: "&c&l[!] &fPlayer &c%player% &fnot found!"
commandNotFound: "&c&l[!] &fCommand &c%command% &fnot found!"
noPermission: "&c&l[!] &fYou don´t have permission to use &c/%command%&f!"